### PR TITLE
Improve clarity of field names

### PR DESCRIPTION
**Pull request by joostlek**

### CODE REVIEW

**Comment by joostlek** [comment]
@airgradienthq Can you maybe shed some light on the variable names used here? I think it would be nice if they were correct, clear, and in line with what is used in the device/app/wherever else

**Comment by joostlek** [comment]
FYI: the left side is the name of the field we are going to use as return value, whatever is inside the `field(metadata=field_options(alias="xxx"))` is from the JSON we receive from the device

**Comment by airgradienthq** [comment]
> @airgradienthq Can you maybe shed some light on the variable names used here? I think it would be nice if they were correct, clear, and in line with what is used in the device/app/wherever else

It looks good in your PR. Raw are the direct values (resistance of the MoX) for volatile organic compounds and Nitrogen Oxides from the Sensirion SGP41 sensor. The index values are calculated values based on the raw values by the Sensirion gas index library.

**Comment by joostlek** [comment]
Can you also check the rest? I pushed that part to master and now the test coverage is up to date I will work in PRs so this PR doesn't change the other lines, but I would like to have a second pair of eyes on the naming :)

**Comment by airgradienthq** [comment]
> Can you also check the rest? I pushed that part to master and now the test coverage is up to date I will work in PRs so this PR doesn't change the other lines, but I would like to have a second pair of eyes on the naming :)

Yes I had a look. Looks good to me!

**Pull request merged**
